routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', function () {
	// return redirect()->route('login');
	return redirect()->route('pemerintah.index');
})->name('/');


Route::group(['as' => 'auth.'], function (){
	Route::post('auth/login', 'Auth\LoginController@login')->name('login');
});

Route::group(['as' => 'pemerintah.'], function (){

	Route::get('index', 'Backend\PemerintahController@index')->name('index');
	Route::get('about', 'Backend\PemerintahController@about')->name('about');
	Route::get('contact', 'Backend\PemerintahController@contact')->name('contact');
	Route::get('detaildinas', 'Backend\PemerintahController@detaildinas')->name('detaildinas');
	Route::get('iku', 'Backend\PemerintahController@iku')->name('iku');
	Route::get('rkt', 'Backend\PemerintahController@rkt')->name('rkt');
	Route::get('pk', 'Backend\PemerintahController@pk')->name('pk');
	Route::get('pkperubahan', 'Backend\PemerintahController@pkperubahan')->name('pkperubahan');
	Route::get('rencanaaksi', 'Backend\PemerintahController@rencanaaksi')->name('rencanaaksi');
	Route::get('program', 'Backend\PemerintahController@program')->name('program');
	Route::get('detailpelaporan', 'Backend\PemerintahController@detailpelaporan')->name('detailpelaporan');
	Route::get('detailpengukuran', 'Backend\PemerintahController@detailpengukuran')->name('detailpengukuran');


	// Route::get('changetahun/{tahun}', 'Backend\PemerintahController@changetahun')->name('changetahun');
	Route::any('gantitahun/{tahun}', 'Backend\PemerintahController@gantitahun')->name('gantitahun');

	Route::any('perencanaan/{id}/{idsasaran}/{idjabatan}', 'Backend\PemerintahController@perencanaan')->name('perencanaan');
	Route::any('pengukuran/{id}/{idsasaran}', 'Backend\PemerintahController@pengukuran')->name('pengukuran');
	Route::any('pelaporan/{id}/{idsasaran}', 'Backend\PemerintahController@pelaporan')->name('pelaporan');
	Route::any('evaluasi', 'Backend\PemerintahController@evaluasi')->name('evaluasi');
});


Auth::routes();

Route::group([
	'namespace' => 'Backend',
	'prefix' => 'backend',
	'as' => 'backend.',
	'middleware' => 'auth',
], function () {

	// Route::get('home', 'HomeController@index')->name('home')->middleware('auth-menu');
	Route::get('home', 'HomeController@index')->name('home');



    /*
	 * RPJMD/RENSTRA Modul Routes
	 * route('web.rpjmd')
	 * route('web.rpjmd.detail')
	 */
	Route::group(['as' => 'rpjmd.'], function (){
		Route::get('rpjmd', 'RpjmdController@index')->name('index');
		Route::get('rpjmd/masukoperator', 'RpjmdController@masukoperator')->name('masukoperator');
		Route::get('rpjmd/masuk/{id}/{tahun}', 'RpjmdController@masuk')->name('masuk');
		Route::get('rpjmd/visidetail/{id}/{ids}', 'RpjmdController@visidetail')->name('visidetail');
		Route::get('rpjmd/tambahmisi/{id}/{ids}', 'RpjmdController@tambahmisi')->name('tambahmisi');
		Route::get('rpjmd/tambahtujuan/{id}/{ids}', 'RpjmdController@tambahtujuan')->name('tambahtujuan');
		Route::get('rpjmd/tambahindikatortujuan/{id}/{ids}', 'RpjmdController@tambahindikatortujuan')->name('tambahindikatortujuan');
		Route::get('rpjmd/tambahindikatorsasaran/{id}/{ids}', 'RpjmdController@tambahindikatorsasaran')->name('tambahindikatorsasaran');
		Route::get('rpjmd/tambahsasaran/{id}/{ids}', 'RpjmdController@tambahsasaran')->name('tambahsasaran');
		Route::get('rpjmd/tambahprogram/{id}/{ids}', 'RpjmdController@tambahprogram')->name('tambahprogram');
		Route::get('rpjmd/misidetail/{id}/{ids}', 'RpjmdController@misidetail')->name('misidetail');
		Route::get('rpjmd/tujuandetail/{id}/{ids}', 'RpjmdController@tujuandetail')->name('tujuandetail');
		Route::get('rpjmd/sasarandetail/{id}/{ids}', 'RpjmdController@sasarandetail')->name('sasarandetail');
		Route::get('rpjmd/detailsasaranindikator/{id}/{ids}', 'RpjmdController@detailsasaranindikator')->name('detailsasaranindikator');
		Route::get('rpjmd/detailtujuanindikator/{id}/{ids}', 'RpjmdController@detailtujuanindikator')->name('detailtujuanindikator');
		Route::get('rpjmd/tujuan/{id}/{tahun}/{ids}', 'RpjmdController@tujuan')->name('tujuan');
		Route::get('rpjmd/program/{id}/{ids}', 'RpjmdController@program')->name('program');
		Route::post('rpjmd/deletevisi', 'RpjmdController@deletevisi')->name('deletevisi');
		Route::post('rpjmd/deletemisi', 'RpjmdController@deletemisi')->name('deletemisi');
		Route::post('rpjmd/deletetujuan', 'RpjmdController@deletetujuan')->name('deletetujuan');
		Route::post('rpjmd/deletesasaran', 'RpjmdController@deletesasaran')->name('deletesasaran');
		Route::post('rpjmd/deleteindikatorsasaran', 'RpjmdController@deleteindikatorsasaran')->name('deleteindikatorsasaran');
		Route::post('rpjmd/savevisi', 'RpjmdController@savevisi')->name('savevisi');
		Route::post('rpjmd/editvisi', 'RpjmdController@editvisi')->name('editvisi');
		Route::post('rpjmd/savemisi', 'RpjmdController@savemisi')->name('savemisi');
		Route::post('rpjmd/editmisi', 'RpjmdController@editmisi')->name('editmisi');
		Route::post('rpjmd/savetujuan', 'RpjmdController@savetujuan')->name('savetujuan');
		Route::post('rpjmd/edittujuan', 'RpjmdController@edittujuan')->name('edittujuan');
		Route::post('rpjmd/editindikatortujuan', 'RpjmdController@editindikatortujuan')->name('editindikatortujuan');
		Route::post('rpjmd/rubahiku', 'RpjmdController@rubahiku')->name('rubahiku');
		Route::post('rpjmd/deleteinditujuan', 'RpjmdController@deleteinditujuan')->name('deleteinditujuan');
		Route::post('rpjmd/saveindikatortujuan', 'RpjmdController@saveindikatortujuan')->name('saveindikatortujuan');
		Route::post('rpjmd/savesasaran', 'RpjmdController@savesasaran')->name('savesasaran');
		Route::post('rpjmd/editsasaran', 'RpjmdController@editsasaran')->name('editsasaran');
		Route::post('rpjmd/editindikatorsasaran', 'RpjmdController@editindikatorsasaran')->name('editindikatorsasaran');
		Route::post('rpjmd/saveindikatorsasaran', 'RpjmdController@saveindikatorsasaran')->name('saveindikatorsasaran');
		Route::post('rpjmd/saveprogram', 'RpjmdController@saveprogram')->name('saveprogram');
		// Route::get('role/edit/{id}', 'RoleController@edit')->name('edit');
		// Route::post('role/update/{id}', 'RoleController@update')->name('update');
		// Route::get('role/delete/{id}', 'RoleController@delete')->name('delete');
	});

	/**
	 * Change Password Modul Routes
	 * route('backend.change-password.*')
	 */
	Route::group(['as' => 'change-password.'], function (){
		Route::get('change-password', 'ChangePasswordController@index')->name('index');
		Route::post('change-password/change', 'ChangePasswordController@change')->name('change');
	});

	/**
	 * Profile Modul Routes
	 * route('backend.profile.*')
	 */
	Route::group(['as' => 'profile.'], function (){
		Route::get('profile', 'ProfileController@index')->name('index');
		Route::post('profile/update', 'ProfileController@update')->name('update');
	});

	/**
	 * User Modul Routes
	 * route('backend.user.*')
	 */
	Route::group(['as' => 'user.'], function (){
		Route::get('user', 'UserController@index')->name('index');
		Route::post('user/toggle', 'UserController@toggle')->name('toggle');
		Route::get('user/create', 'UserController@create')->name('create');
		Route::post('user/store', 'UserController@store')->name('store');
		Route::get('user/edit/{id}', 'UserController@edit')->name('edit');
		Route::get('editprofile/edit/{id}', 'UserController@editprofile')->name('editprofile');
		Route::post('user/update/{id}', 'UserController@update')->name('update');
	});

	/**
	 * Roles Modul Routes
	 * route('backend.role.*')
	 */
	Route::group(['as' => 'role.'], function (){
		Route::get('role', 'RoleController@index')->name('index')->middleware('auth-menu');
		Route::post('role/toggle', 'RoleController@toggle')->name('toggle');
		Route::get('role/create', 'RoleController@create')->name('create');
		Route::post('role/store', 'RoleController@store')->name('store');
		Route::get('role/edit/{id}', 'RoleController@edit')->name('edit');
		Route::post('role/update/{id}', 'RoleController@update')->name('update');
	});

	/**
	 * Menus Modul Routes
	 * route('backend.menu.*')
	 */
	Route::group(['as' => 'menu.'], function (){
		Route::get('menu', 'MenuController@index')->name('index');
		Route::post('menu/toggle', 'MenuController@toggle')->name('toggle');
		Route::get('menu/create', 'MenuController@create')->name('create');
		Route::post('menu/store', 'MenuController@store')->name('store');
		Route::get('menu/edit/{id}', 'MenuController@edit')->name('edit');
		Route::post('menu/update/{id}', 'MenuController@update')->name('update');
	});

	/**
	 * Access Control Modul Routes
	 * route('backend.accesscontrol.*')
	 */
	Route::group(['as' => 'accesscontrol.'], function (){
		Route::get('accesscontrol', 'AccessControlController@index')->name('index');
		Route::post('accesscontrol/update', 'AccessControlController@update')->name('update');
	});

	 /*
	 * Dinas Modul Routes
	 * route('web.dinas')
	 * route('web.dinas.detail')
	 */
		Route::group(['as' => 'dinas.'], function (){
			Route::get('dinas', 'DinasController@index')->name('index');
			Route::get('dinas/tambahdinas', 'DinasController@tambahdinas')->name('tambahdinas');
			Route::get('dinas/copydinas', 'DinasController@copydinas')->name('copydinas');
			Route::get('dinas/editdinas/{id}', 'DinasController@editdinas')->name('editdinas');
			Route::get('dinas/eselon/{id}', 'DinasController@eselon')->name('eselon');
			Route::get('dinas/tambaheselon/{id}', 'DinasController@tambaheselon')->name('tambaheselon');
			Route::get('dinas/addeselon/{id}/{ids}', 'DinasController@addeselon')->name('addeselon');

app/Http/Controllers/Backend.bak/AccessControlController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\AccessControl\AccessControlRepositoryInterface;
use App\Repositories\Role\RoleRepositoryInterface;
use App\Traits\FlashMessageTraits;
use DB;
class AccessControlController extends Controller
{
    use FlashMessageTraits;

    function __construct(
        AccessControlRepositoryInterface $accessControlRepo,
        RoleRepositoryInterface $roleRepo
    )
	{
        $this->accessControlRepo = $accessControlRepo;
        $this->roleRepo = $roleRepo;
        
        //No session access from constructor work arround
        $this->middleware(function ($request, $next)
        {
            $this->user = session('data')->user;
            return $next($request);
        });
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $request = request();
        
        // If request id is unset
        (!isset($request->id)) ? $role_id = $this->user->role_id : $role_id = $this->decryptingId($request->id) ;

        $roles = DB::select("SELECT * FROM roles WHERE status = 1 and id not in(99) order by role asc");
        $access = $this->accessControlRepo->access($role_id);

        return
            view('backend.accesscontrol.index')
            ->with('roles', $roles)
            ->with('accesscontrols', $access)
        ;
    }

    /**
     * 
     */
    public function update(Request $request)
    {
        $request->merge(['role' => $this->decryptingId($request->role) ]);
        $response = $this->accessControlRepo->update($request);
        $this->message($response->level, $response->message);
        return back();
    }

}

app/Http/Controllers/Backend/AccessControlController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\AccessControl\AccessControlRepositoryInterface;
use App\Repositories\Role\RoleRepositoryInterface;
use App\Traits\FlashMessageTraits;
use DB;
class AccessControlController extends Controller
{
    use FlashMessageTraits;

    function __construct(
        AccessControlRepositoryInterface $accessControlRepo,
        RoleRepositoryInterface $roleRepo
    )
	{
        $this->accessControlRepo = $accessControlRepo;
        $this->roleRepo = $roleRepo;
        
        //No session access from constructor work arround
        $this->middleware(function ($request, $next)
        {
            $this->user = session('data')->user;
            return $next($request);
        });
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $request = request();
        
        // If request id is unset
        (!isset($request->id)) ? $role_id = $this->user->role_id : $role_id = $this->decryptingId($request->id) ;

        $roles = DB::select("SELECT * FROM roles WHERE status = 1 and id not in(99) order by role asc");
        $access = $this->accessControlRepo->access($role_id);

        return
            view('backend.accesscontrol.index')
            ->with('roles', $roles)
            ->with('accesscontrols', $access)
        ;
    }

    /**
     * 
     */
    public function update(Request $request)
    {
        $request->merge(['role' => $this->decryptingId($request->role) ]);
        $response = $this->accessControlRepo->update($request);
        $this->message($response->level, $response->message);
        return back();
    }

}

app/Http/Controllers/Backend/ChangePasswordController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\User\UserRepositoryInterface;
use App\Traits\FlashMessageTraits;
use Auth;

class ChangePasswordController extends Controller
{
    use FlashMessageTraits;

    function __construct(
        UserRepositoryInterface $userRepo
    ) {
        $this->userRepo     = $userRepo;
        $this->_pass_regex  = config('setting.pass.regex');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return
            view('backend.change-password')
        ;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function change(Request $request)
    {
        //
        $request->validate([
            'current_password' => 'required',
            'new_password' => 'required|string|min:8|confirmed|'.$this->_pass_regex,
        ]);
        $id = Auth::user()->id;
        $response = $this->userRepo->changePassword($id, $request);
        $this->message($response->level, $response->message);
        return redirect()->route('backend.change-password.index');
    }

    

}

app/Http/Controllers/Backend/EvaluasikinerjaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use App\Models\User;
use App\Models\UserValidation;
use App\Models\Role;
use Carbon\Carbon;
use DB;
/**
 * Class UserController.
 */
class EvaluasikinerjaController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */

	function __construct()
	{
		$this->middleware(['auth']);
	}

	public function index()
    {
		$data['breadcrumb'] = [
            'parent' => 'Evaluasi Kinerja',
            'child' => 'List Evaluasi Mandiri'
		];

		$data['listdinas'] = $this->listdinas();
		return view('backend.evaluasikinerja.index', $data);
	}


	public function detail($id, $tahun)
    {
		$query = DB::select("SELECT * FROM tbl_evaluasi WHERE iddinas = ".$id." AND tahun = ".$_COOKIE['tahun']);
		$data['evaluasi'] = $query;
        $data['id'] = $id;

		return view('backend.evaluasikinerja.detail', $data);
	}

	public function listdinas(){
		$hasil = DB::select('SELECT aa.td_id, aa.td_dinas, aa.td_keterangan , bb.nilai
								FROM
										(
										SELECT a.td_id, a.td_dinas, a.td_keterangan
										FROM tbl_dinas a
										WHERE
											a.status = 1

                                            and deleted_at is not null
										)aa
								LEFT JOIN
										(
										SELECT a.td_id, a.td_dinas, a.td_keterangan , b.nilai
										FROM tbl_dinas a
										LEFT JOIN tbl_evaluasi b on a.td_id = b.iddinas
										where
											status = 1

                                            and deleted_at is null
											AND b.tahun = '.$_COOKIE['tahun'].'
										)bb on bb.td_id = aa.td_id ');
		return $hasil;
	}


	public function nilaievaluasiedit(Request $request){
		$input = $request->all();
		$data = DB::table('tbl_evaluasi')
				->where('iddinas', $input['idsasaran'])
				->where('tahun', $input['tahun'])
				->update(['nilai' => $input['target']]);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'Nilai Sukses Terupdate!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'Error Ketika Memasukan Ke Database' );
			return response()->json($result);
		}
	}


	public function nilaievaluasi(Request $request){
		$input = $request->all();
		$data = DB::table('tbl_evaluasi')->insert(
			['iddinas' => $input['idsasaran'], 'nilai' => $input['target'], 'tahun' => $input['tahun']]
		);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'Nilai Sukses Tersimpan!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'Error Ketika Memasukan Ke Database' );
			return response()->json($result);
		}
	}

}

resources/views/backend/accesscontrol/index.blade.php
@extends('backend.layouts.app')

@section('content')

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">

                <h5>Access Control List | <strong>ACL</strong></h5>
                <div class="ibox-tools"></div>
            </div>
            <div class="ibox-content">
                <form class="m-t" role="form" method='GET' action="{{ route('backend.accesscontrol.index') }}">
                    @csrf
                    <div class="form-group">
                        <label for="id">{{ __('Role User') }}</label>
                        <select
                            id="id"
                            name="id"
                            class="form-control{{ $errors->has('id') ? ' is-invalid' : '' }}"
                            parsley-trigger="change"
                            required
                            onchange="this.form.submit()"
                        >
                            <option value="" disabled selected>{{ __('Choose Role') }}</option>

                            @foreach ($roles as $role)

                                @if ( request()->get('id') && Crypt::decrypt(request()->get('id')) == $role->id)
                                    <option value="{{ Crypt::encrypt($role->id) }}" selected>{{ $role->role }}</option>
                                @else
                                    <option value="{{ Crypt::encrypt($role->id) }}">{{ $role->role }}</option>
                                @endif

                            @endforeach
                        </select>
                    </div>
                </form>

                <div id="nestable-menu">
                    <button type="button" data-action="expand-all" class="btn btn-white btn-sm">Expand All</button>
                    <button type="button" data-action="collapse-all" class="btn btn-white btn-sm">Collapse All</button>
                </div>

                <form method='POST' role="form" action="{{ route('backend.accesscontrol.update') }}">
                    @csrf
                    <input type="hidden" name="role" id="role"/>
                    <div class="dd" id="nestable2">
                        <ol class="dd-list">

                        @foreach($accesscontrols->menus as $menu)
                        @if($menu->parent == config('setting.value.zero'))
                            @if($menu->route == config('setting.url.crash'))
                                <li class="dd-item godfather-li" data-id="{{ $menu->id }}">
                                    <div class="dd-handle">
                                        <input
                                            type="checkbox"
                                            name="menus[]"
                                            id="{{ $menu->id }}"
                                            value="{{ $menu->id }}"
                                            class="i-checks"
                                            {{ (in_array($menu->id, $accesscontrols->pivot)) ? 'Checked' : '' }}
                                        />
                                        {{ $menu->label }}
                                    </div>
                                    <ol class="dd-list">

                                        @foreach($accesscontrols->menus as $menu2)
                                        @if($menu2->parent == $menu->id)

                                            <li class="dd-item parents-li-{{ $menu->id }} parent-li" data-id="{{ $menu2->id }}">
                                                <div class="dd-handle">
                                                    <input
                                                        type="checkbox"
                                                        name="menus[]"
                                                        id="{{ $menu2->id }}"
                                                        value="{{ $menu2->id }}"
                                                        class="i-checks"
                                                        {{ (in_array($menu2->id, $accesscontrols->pivot)) ? 'Checked' : '' }}
                                                    />
                                                    {{ $menu2->label }}
                                                </div>
                                                <ol class="dd-list">
                                                    @foreach($accesscontrols->menus as $menu3)
                                                    @if($menu3->parent == $menu2->id)

                                                        <li class="dd-item child-li-{{ $menu2->id }}" data-id="{{ $menu3->id }}">
                                                            <div class="dd-handle">
                                                                <input
                                                                    type="checkbox"
                                                                    name="menus[]"
                                                                    id="{{ $menu3->id }}"
                                                                    value="{{ $menu3->id }}"
                                                                    class="i-checks"
                                                                    {{ (in_array($menu3->id, $accesscontrols->pivot)) ? 'Checked' : '' }}
                                                                />
                                                                {{ $menu3->label }}
                                                            </div>
                                                        </li>
                                                    @endif
                                                    @endforeach
                                                </ol>
                                            </li>

                                        @endif
                                        @endforeach

                                    </ol>
                                </li>
                            @else
                                <li class="dd-item" data-id="{{ $menu->id }}">
                                    <div class="dd-handle">
                                        <style>.m-r-xs { margin-right: 7px; }</style>
                                        <i class="m-r-xs text-muted fa fa-ellipsis-h"></i>
                                        <input
                                            type="checkbox"
                                            name="menus[]"
                                            id="{{ $menu->id }}"
                                            value="{{ $menu->id }}"
                                            class="i-checks"
                                            {{ (in_array($menu->id, $accesscontrols->pivot)) ? 'Checked' : '' }}
                                        />
                                        {{ $menu->label }}
                                    </div>
                                </li>
                            @endif
                        @endif

                        @endforeach
                        </ol>
                    </div>

                    <button type="submit"
					    class="pull-right btn btn-md waves-effect waves-light btn-success m-b-5 update-access-control"
					    data-toggle="tooltip"
                        data-placement="top"
                    >
						<i class="fa fa-pencil"></i>
						<strong>UPDATE</strong>
                    </button>

                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

@section('onpage-js')

    @include('backend.layouts.message')

    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

            // activate Nestable for list 2
            $('#nestable2').nestable({
                group: 1,
                maxDepth: 0
            }).nestable('collapseAll');

            $('#nestable-menu').on('click', function (e) {
                var target = $(e.target),
                action = target.data('action');
                if (action === 'expand-all') {
                    $('.dd').nestable('expandAll');
                }
                if (action === 'collapse-all') {
                    $('.dd').nestable('collapseAll');
                }
            });

            $('.update-access-control').on('click',function(e){
                e.preventDefault();

                $('#role').val( $('#id').val() );
                if(!$('#role').val())
                {
                    swal({
                        title: "Warning",
                        text: "Pick a Role !",
                        type: "warning"
                    });
                    return false;
                }

                var form = $(this).parents('form');

                swal({
                    title: "Are you sure?",
                    text: "This will affected to user in this role",
                    type: "info",
                    showCancelButton: true,
                    confirmButtonClass: 'btn-primary waves-effect waves-light',
                    confirmButtonText: 'Update!',
                    closeOnConfirm: true,
                    dangerMode: true,
                }, function (isConfirm) {
                    if (isConfirm) {
                        form.submit();
                        $('.update-access-control').attr('disabled', 'disabled');
                    } else {
                        swal("Canceled !");
                        $('.update-access-control').removeAttr('disabled');
                    }
                });
            });

            $('.godfather-li input[name="menus[]"]').on('ifChecked', function (e) {
                var parent_id = $(this).attr("id");
                $('.parents-li-'+parent_id+' input[name="menus[]"]').iCheck('check');
            })
            $('.godfather-li input[name="menus[]"]').on('ifUnchecked', function (e) {
                var parent_id = $(this).attr("id");
                $('.parents-li-'+parent_id+' input[name="menus[]"]').iCheck('uncheck');
            })
            $('.parent-li input[name="menus[]"]').on('ifChecked', function (e) {
                var parent_id = $(this).attr("id");
                $('.child-li-'+parent_id+' input[name="menus[]"]').iCheck('check');
            })
            $('.parent-li input[name="menus[]"]').on('ifUnchecked', function (e) {
                var parent_id = $(this).attr("id");
                $('.child-li-'+parent_id+' input[name="menus[]"]').iCheck('uncheck');
            })

        });
    </script>
@endsection