routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', function () {
	// return redirect()->route('login');
	return redirect()->route('pemerintah.index');
})->name('/');


Route::group(['as' => 'auth.'], function (){
	Route::post('auth/login', 'Auth\LoginController@login')->name('login');
});

Route::group(['as' => 'pemerintah.'], function (){

	Route::get('index', 'Backend\PemerintahController@index')->name('index');
	Route::get('about', 'Backend\PemerintahController@about')->name('about');
	Route::get('contact', 'Backend\PemerintahController@contact')->name('contact');
	Route::get('detaildinas', 'Backend\PemerintahController@detaildinas')->name('detaildinas');
	Route::get('iku', 'Backend\PemerintahController@iku')->name('iku');
	Route::get('rkt', 'Backend\PemerintahController@rkt')->name('rkt');
	Route::get('pk', 'Backend\PemerintahController@pk')->name('pk');
	Route::get('pkperubahan', 'Backend\PemerintahController@pkperubahan')->name('pkperubahan');
	Route::get('rencanaaksi', 'Backend\PemerintahController@rencanaaksi')->name('rencanaaksi');
	Route::get('program', 'Backend\PemerintahController@program')->name('program');
	Route::get('detailpelaporan', 'Backend\PemerintahController@detailpelaporan')->name('detailpelaporan');
	Route::get('detailpengukuran', 'Backend\PemerintahController@detailpengukuran')->name('detailpengukuran');


	// Route::get('changetahun/{tahun}', 'Backend\PemerintahController@changetahun')->name('changetahun');
	Route::any('gantitahun/{tahun}', 'Backend\PemerintahController@gantitahun')->name('gantitahun');

	Route::any('perencanaan/{id}/{idsasaran}/{idjabatan}', 'Backend\PemerintahController@perencanaan')->name('perencanaan');
	Route::any('pengukuran/{id}/{idsasaran}', 'Backend\PemerintahController@pengukuran')->name('pengukuran');
	Route::any('pelaporan/{id}/{idsasaran}', 'Backend\PemerintahController@pelaporan')->name('pelaporan');
	Route::any('evaluasi', 'Backend\PemerintahController@evaluasi')->name('evaluasi');
});


Auth::routes();

Route::group([
	'namespace' => 'Backend',
	'prefix' => 'backend',
	'as' => 'backend.',
	'middleware' => 'auth',
], function () {

	// Route::get('home', 'HomeController@index')->name('home')->middleware('auth-menu');
	Route::get('home', 'HomeController@index')->name('home');



    /*
	 * RPJMD/RENSTRA Modul Routes
	 * route('web.rpjmd')
	 * route('web.rpjmd.detail')
	 */
	Route::group(['as' => 'rpjmd.'], function (){
		Route::get('rpjmd', 'RpjmdController@index')->name('index');
		Route::get('rpjmd/masukoperator', 'RpjmdController@masukoperator')->name('masukoperator');
		Route::get('rpjmd/masuk/{id}/{tahun}', 'RpjmdController@masuk')->name('masuk');
		Route::get('rpjmd/visidetail/{id}/{ids}', 'RpjmdController@visidetail')->name('visidetail');
		Route::get('rpjmd/tambahmisi/{id}/{ids}', 'RpjmdController@tambahmisi')->name('tambahmisi');
		Route::get('rpjmd/tambahtujuan/{id}/{ids}', 'RpjmdController@tambahtujuan')->name('tambahtujuan');
		Route::get('rpjmd/tambahindikatortujuan/{id}/{ids}', 'RpjmdController@tambahindikatortujuan')->name('tambahindikatortujuan');
		Route::get('rpjmd/tambahindikatorsasaran/{id}/{ids}', 'RpjmdController@tambahindikatorsasaran')->name('tambahindikatorsasaran');
		Route::get('rpjmd/tambahsasaran/{id}/{ids}', 'RpjmdController@tambahsasaran')->name('tambahsasaran');
		Route::get('rpjmd/tambahprogram/{id}/{ids}', 'RpjmdController@tambahprogram')->name('tambahprogram');
		Route::get('rpjmd/misidetail/{id}/{ids}', 'RpjmdController@misidetail')->name('misidetail');
		Route::get('rpjmd/tujuandetail/{id}/{ids}', 'RpjmdController@tujuandetail')->name('tujuandetail');
		Route::get('rpjmd/sasarandetail/{id}/{ids}', 'RpjmdController@sasarandetail')->name('sasarandetail');
		Route::get('rpjmd/detailsasaranindikator/{id}/{ids}', 'RpjmdController@detailsasaranindikator')->name('detailsasaranindikator');
		Route::get('rpjmd/detailtujuanindikator/{id}/{ids}', 'RpjmdController@detailtujuanindikator')->name('detailtujuanindikator');
		Route::get('rpjmd/tujuan/{id}/{tahun}/{ids}', 'RpjmdController@tujuan')->name('tujuan');
		Route::get('rpjmd/program/{id}/{ids}', 'RpjmdController@program')->name('program');
		Route::post('rpjmd/deletevisi', 'RpjmdController@deletevisi')->name('deletevisi');
		Route::post('rpjmd/deletemisi', 'RpjmdController@deletemisi')->name('deletemisi');
		Route::post('rpjmd/deletetujuan', 'RpjmdController@deletetujuan')->name('deletetujuan');
		Route::post('rpjmd/deletesasaran', 'RpjmdController@deletesasaran')->name('deletesasaran');
		Route::post('rpjmd/deleteindikatorsasaran', 'RpjmdController@deleteindikatorsasaran')->name('deleteindikatorsasaran');
		Route::post('rpjmd/savevisi', 'RpjmdController@savevisi')->name('savevisi');
		Route::post('rpjmd/editvisi', 'RpjmdController@editvisi')->name('editvisi');
		Route::post('rpjmd/savemisi', 'RpjmdController@savemisi')->name('savemisi');
		Route::post('rpjmd/editmisi', 'RpjmdController@editmisi')->name('editmisi');
		Route::post('rpjmd/savetujuan', 'RpjmdController@savetujuan')->name('savetujuan');
		Route::post('rpjmd/edittujuan', 'RpjmdController@edittujuan')->name('edittujuan');
		Route::post('rpjmd/editindikatortujuan', 'RpjmdController@editindikatortujuan')->name('editindikatortujuan');
		Route::post('rpjmd/rubahiku', 'RpjmdController@rubahiku')->name('rubahiku');
		Route::post('rpjmd/deleteinditujuan', 'RpjmdController@deleteinditujuan')->name('deleteinditujuan');
		Route::post('rpjmd/saveindikatortujuan', 'RpjmdController@saveindikatortujuan')->name('saveindikatortujuan');
		Route::post('rpjmd/savesasaran', 'RpjmdController@savesasaran')->name('savesasaran');
		Route::post('rpjmd/editsasaran', 'RpjmdController@editsasaran')->name('editsasaran');
		Route::post('rpjmd/editindikatorsasaran', 'RpjmdController@editindikatorsasaran')->name('editindikatorsasaran');
		Route::post('rpjmd/saveindikatorsasaran', 'RpjmdController@saveindikatorsasaran')->name('saveindikatorsasaran');
		Route::post('rpjmd/saveprogram', 'RpjmdController@saveprogram')->name('saveprogram');
		// Route::get('role/edit/{id}', 'RoleController@edit')->name('edit');
		// Route::post('role/update/{id}', 'RoleController@update')->name('update');
		// Route::get('role/delete/{id}', 'RoleController@delete')->name('delete');
	});

	/**
	 * Change Password Modul Routes
	 * route('backend.change-password.*')
	 */
	Route::group(['as' => 'change-password.'], function (){
		Route::get('change-password', 'ChangePasswordController@index')->name('index');
		Route::post('change-password/change', 'ChangePasswordController@change')->name('change');
	});

	/**
	 * Profile Modul Routes
	 * route('backend.profile.*')
	 */
	Route::group(['as' => 'profile.'], function (){
		Route::get('profile', 'ProfileController@index')->name('index');
		Route::post('profile/update', 'ProfileController@update')->name('update');
	});

	/**
	 * User Modul Routes
	 * route('backend.user.*')
	 */
	Route::group(['as' => 'user.'], function (){
		Route::get('user', 'UserController@index')->name('index');
		Route::post('user/toggle', 'UserController@toggle')->name('toggle');
		Route::get('user/create', 'UserController@create')->name('create');
		Route::post('user/store', 'UserController@store')->name('store');
		Route::get('user/edit/{id}', 'UserController@edit')->name('edit');
		Route::get('editprofile/edit/{id}', 'UserController@editprofile')->name('editprofile');
		Route::post('user/update/{id}', 'UserController@update')->name('update');
	});

	/**
	 * Roles Modul Routes
	 * route('backend.role.*')
	 */
	Route::group(['as' => 'role.'], function (){
		Route::get('role', 'RoleController@index')->name('index')->middleware('auth-menu');
		Route::post('role/toggle', 'RoleController@toggle')->name('toggle');
		Route::get('role/create', 'RoleController@create')->name('create');
		Route::post('role/store', 'RoleController@store')->name('store');
		Route::get('role/edit/{id}', 'RoleController@edit')->name('edit');
		Route::post('role/update/{id}', 'RoleController@update')->name('update');
	});

	/**
	 * Menus Modul Routes
	 * route('backend.menu.*')
	 */
	Route::group(['as' => 'menu.'], function (){
		Route::get('menu', 'MenuController@index')->name('index');
		Route::post('menu/toggle', 'MenuController@toggle')->name('toggle');
		Route::get('menu/create', 'MenuController@create')->name('create');
		Route::post('menu/store', 'MenuController@store')->name('store');
		Route::get('menu/edit/{id}', 'MenuController@edit')->name('edit');
		Route::post('menu/update/{id}', 'MenuController@update')->name('update');
	});

	/**
	 * Access Control Modul Routes
	 * route('backend.accesscontrol.*')
	 */
	Route::group(['as' => 'accesscontrol.'], function (){
		Route::get('accesscontrol', 'AccessControlController@index')->name('index');
		Route::post('accesscontrol/update', 'AccessControlController@update')->name('update');
	});

	 /*
	 * Dinas Modul Routes
	 * route('web.dinas')
	 * route('web.dinas.detail')
	 */
		Route::group(['as' => 'dinas.'], function (){
			Route::get('dinas', 'DinasController@index')->name('index');
			Route::get('dinas/tambahdinas', 'DinasController@tambahdinas')->name('tambahdinas');
			Route::get('dinas/copydinas', 'DinasController@copydinas')->name('copydinas');
			Route::get('dinas/editdinas/{id}', 'DinasController@editdinas')->name('editdinas');
			Route::get('dinas/eselon/{id}', 'DinasController@eselon')->name('eselon');
			Route::get('dinas/tambaheselon/{id}', 'DinasController@tambaheselon')->name('tambaheselon');
			Route::get('dinas/addeselon/{id}/{ids}', 'DinasController@addeselon')->name('addeselon');

app/Http/Controllers/Backend/AccessControlController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\AccessControl\AccessControlRepositoryInterface;
use App\Repositories\Role\RoleRepositoryInterface;
use App\Traits\FlashMessageTraits;
use DB;
class AccessControlController extends Controller
{
    use FlashMessageTraits;

    function __construct(
        AccessControlRepositoryInterface $accessControlRepo,
        RoleRepositoryInterface $roleRepo
    )
	{
        $this->accessControlRepo = $accessControlRepo;
        $this->roleRepo = $roleRepo;
        
        //No session access from constructor work arround
        $this->middleware(function ($request, $next)
        {
            $this->user = session('data')->user;
            return $next($request);
        });
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $request = request();
        
        // If request id is unset
        (!isset($request->id)) ? $role_id = $this->user->role_id : $role_id = $this->decryptingId($request->id) ;

        $roles = DB::select("SELECT * FROM roles WHERE status = 1 and id not in(99) order by role asc");
        $access = $this->accessControlRepo->access($role_id);

        return
            view('backend.accesscontrol.index')
            ->with('roles', $roles)
            ->with('accesscontrols', $access)
        ;
    }

    /**
     * 
     */
    public function update(Request $request)
    {
        $request->merge(['role' => $this->decryptingId($request->role) ]);
        $response = $this->accessControlRepo->update($request);
        $this->message($response->level, $response->message);
        return back();
    }

}

app/Http/Controllers/Backend/ChangePasswordController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\User\UserRepositoryInterface;
use App\Traits\FlashMessageTraits;
use Auth;

class ChangePasswordController extends Controller
{
    use FlashMessageTraits;

    function __construct(
        UserRepositoryInterface $userRepo
    ) {
        $this->userRepo     = $userRepo;
        $this->_pass_regex  = config('setting.pass.regex');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return
            view('backend.change-password')
        ;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function change(Request $request)
    {
        //
        $request->validate([
            'current_password' => 'required',
            'new_password' => 'required|string|min:8|confirmed|'.$this->_pass_regex,
        ]);
        $id = Auth::user()->id;
        $response = $this->userRepo->changePassword($id, $request);
        $this->message($response->level, $response->message);
        return redirect()->route('backend.change-password.index');
    }

    

}

app/Http/Controllers/Backend/EvaluasikinerjaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use App\Models\User;
use App\Models\UserValidation;
use App\Models\Role;
use Carbon\Carbon;
use DB;
/**
 * Class UserController.
 */
class EvaluasikinerjaController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */

	function __construct()
	{
		$this->middleware(['auth']);
	}

	public function index()
    {
		$data['breadcrumb'] = [
            'parent' => 'Evaluasi Kinerja',
            'child' => 'List Evaluasi Mandiri'
		];

		$data['listdinas'] = $this->listdinas();
		return view('backend.evaluasikinerja.index', $data);
	}


	public function detail($id, $tahun)
    {
		$query = DB::select("SELECT * FROM tbl_evaluasi WHERE iddinas = ".$id." AND tahun = ".$_COOKIE['tahun']);
		$data['evaluasi'] = $query;
        $data['id'] = $id;

		return view('backend.evaluasikinerja.detail', $data);
	}

	public function listdinas(){
		$hasil = DB::select('SELECT aa.td_id, aa.td_dinas, aa.td_keterangan , bb.nilai
								FROM
										(
										SELECT a.td_id, a.td_dinas, a.td_keterangan
										FROM tbl_dinas a
										WHERE
											a.status = 1

                                            and deleted_at is not null
										)aa
								LEFT JOIN
										(
										SELECT a.td_id, a.td_dinas, a.td_keterangan , b.nilai
										FROM tbl_dinas a
										LEFT JOIN tbl_evaluasi b on a.td_id = b.iddinas
										where
											status = 1

                                            and deleted_at is null
											AND b.tahun = '.$_COOKIE['tahun'].'
										)bb on bb.td_id = aa.td_id ');
		return $hasil;
	}


	public function nilaievaluasiedit(Request $request){
		$input = $request->all();
		$data = DB::table('tbl_evaluasi')
				->where('iddinas', $input['idsasaran'])
				->where('tahun', $input['tahun'])
				->update(['nilai' => $input['target']]);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'Nilai Sukses Terupdate!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'Error Ketika Memasukan Ke Database' );
			return response()->json($result);
		}
	}


	public function nilaievaluasi(Request $request){
		$input = $request->all();
		$data = DB::table('tbl_evaluasi')->insert(
			['iddinas' => $input['idsasaran'], 'nilai' => $input['target'], 'tahun' => $input['tahun']]
		);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'Nilai Sukses Tersimpan!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'Error Ketika Memasukan Ke Database' );
			return response()->json($result);
		}
	}

}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.home.home');
    }
}

resources/views/backend/pemerintah - Copy/about.blade.php
@extends('backend.layouts.landing')

@section('title', 'About')

@section('content')
	<section id="about" style="margin-top: 180px">      
        <div class="container">
            <div class="row">
                <section class="page col-sm-9">
                    <h2 class="page-title">Tentang Kami</h2>
                    <div class="entry">

                        <p>Kewenangan Kota Cimahi sebagai Daerah Otonom mencakup seluruh kewenangan bidang pemerintahan, termasuk kewenangan wajib yaitu pekerjaan umum, kesehatan, pendidikan dan kebudayaan, perhubungan, industri dan perdagangan, penanaman modal, lingkungan hidup, pertahanan, koperasi dan tenaga kerja kecuali bidang politik luar negeri, pertahanan keamanan, peradilan, moneter fisikal, agama serta kewenangan bidang lain sesuai dengan peraturan Perundang-undangan Nomor I tahun 2003 tentang Kewenangan Kota Cimahi sebagai Daerah Otonom.</p>                        
                    </div>
                </section>
            </div>
        </div>
    </section>
@endsection

@section('customjs')
@endsection

resources/views/backend/pemerintah - Copy/evaluasi.blade.php
@extends('backend.layouts.landing')
@section('title', 'Evaluasi')

@section('content')
	<section id="about" style="margin-top: 20px">      
        <div class="container" style="width: auto !important">
			<div class="col-md-11" style="margin: 5px" id="up">
			
			<div class="row">
				<div class="col-md-12">
				  <h3>Evaluasi Kinerja <span id="initahun"></span></h3>
				  <br/>
				  <br/>
				</div>
			</div>
			 
			 <div class="row">
				 
				  <div class="col-md-3">
					  <div class="form-group row">
						<label for="colFormLabelSm" class="col-sm-2 " style="margin-top:5px">Tahun</label>
						<div class="col-sm-10">
						<select class="form-control right" id="tahunini" name="tahunini" onChange="tahunnya(this.value)">

						<option disabled selected>Pilih Tahun..</option>
						 <?php
							$already_selected_value = date("Y");
							$earliest_year = 2013;

							foreach (range(date('Y'), $earliest_year) as $x) {
								if($_COOKIE['tahun'] == $x){
									echo '<option value="'.$x.'" selected>'.$x.'</option>';
								}else{
									echo '<option value="'.$x.'">'.$x.'</option>';
								}
								
							}


							?>
						</select>
						</div>
					  </div>
					  
				 </div>
				 <div class="col-md-8">
				 	<a href="{{ route('pemerintah.perencanaan',['id'=>Crypt::encryptString(0), 'idsasaran'=>Crypt::encryptString(0)]) }}" class="btn btn-default "><i class="fa fa-cogs"></i> Perencanaan Kinerja</a>
					<a href="{{ route('pemerintah.pengukuran',['id'=>Crypt::encryptString(0), 'idsasaran'=>Crypt::encryptString(0)]) }}" class="btn btn-default "><i class="fa fa-dashboard"></i> Pengukuran Kinerja</a>
					<a href="{{ route('pemerintah.pelaporan',['id'=>Crypt::encryptString(0), 'idsasaran'=>Crypt::encryptString(0)] ) }}" class="btn btn-default "><i class="fa fa-clipboard"></i> Pelaporan Kinerja</a>
					<a href="{{ route('pemerintah.evaluasi') }}" class="btn btn-default active"><i class="fa fa-check"></i> Evaluasi Kinerja</a>
				</div>
			 </div> 
			 
			 
			</div>
			<div class="col-md-12" style="margin-top: 10px">
				<table id="example" class="table " style="font-size: 12px">
				  <thead>
					<tr>
						<th></th>
						<th><h4>Instansi</h4></th>
						<th>Kategori </th>
					</tr>
				  </thead>

					<tbody>
					
					@php($sl=1)
					 @foreach($data as $dinas)
					 <tr>
						<td>{{$sl}}</td>
						<td>{{$dinas->td_dinas}}</td>
						<td>{{$dinas->nilai}}</td>
					 </tr>
					 
                    @php($sl++)
                    @endforeach
					</tbody>
				</table>
			</div>
		</div>
	</section>
    
@endsection

@section('customjs')
@endsection

resources/views/backend/pemerintah - Copy/index.blade.php
@extends('backend.layouts.landing')

@section('title', 'Home')

@section('content')
     <!-- HOME -->
     <section id="home" data-stellar-background-ratio="0.5" style="background: url({{ asset('images/ch1.jpg') }}); background-size: cover; ">
          <div class="overlay"></div>
          <div class="container">
               <div class="row">

                    <div class="col-md-6 col-sm-12">
                         <div class="home-info">
                              <h1>Selamat Datang di SIAKIP CIMAHI</h1>
                              <a href="#fitur" class="btn section-btn smoothScroll">Fitur Siakip</a>
                              <span>
                                   Lihat di bawah ini
                                   <small>Untuk fitur melihat/mengunduh LAKIP SKPD Kota Cimahi</small>
                              </span>
                         </div>
                    </div>

                    <div class="col-md-6 col-sm-12">
                         <div class="home-video">
                              <div class="embed-responsive embed-responsive-16by9">
                                   <iframe src="https://www.youtube.com/embed/UCaqzifm7BM" frameborder="0" allowfullscreen></iframe>
                              </div>
                         </div>
                    </div>
                    
               </div>
          </div>
     </section>


     <!-- ABOUT -->
     <section id="about" data-stellar-background-ratio="0.5">
          <div class="container">
               <div class="row">

                    <div class="col-md-8 col-sm-8">
                         <div class="about-info">
                              <div class="section-title">
                                   <h2>Selamat Datang di Siakip</h2>
                                   <span class="line-bar">...</span>
                              </div>
                              <p>Sistem Akuntabilitas Kinerja Instansi Pemerintah yang selanjutnya disingkat SAKIP,
									adalah rangkaian sistematik dari berbagai aktivitas, alat, dan prosedur yang dirancang
									untuk tujuan penetapan dan pengukuran, pengumpulan data,
									pengklasifikasian, pengikhtisaran, dan pelaporan kinerja pada instansi pemerintah, dalam rangka
									pertanggungjawaban dan peningkatan kinerja instansi pemerintah.</p>
                  
                         </div>
                    </div>

                    <div class="col-md-4 col-sm-4">
                         <div class="about-image">
                              <img src="images/about-image.jpg" class="img-responsive" alt="">
                         </div>
                    </div>
                    
               </div>
          </div>
     </section>

     <!-- ABOUT -->
     <section id="fitur" data-stellar-background-ratio="0.5">
          <div class="container">
               <div class="row">

                    <div class="col-md-1 col-sm-1">
					          </div>
                    <div class="col-md-5 col-sm-11">
                         <div class="about-image">
                              <img src="images/pns.png" class="img-responsive" style="width: 200px; height: auto" alt="">
                         </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="about-info">
                            <div class="section-title" style="margin-right: 65px">
                                <h2>Fitur Siakip</h2>
                                <span class="line-bar">...</span>
                            </div>
                            <div class="col-md-12">
                              <div class="col-md-4">
                              </div>
                              <div class="portfolio-item apps col-xs-6 col-sm-4 col-md-2">
                                <a href="{{ route('pemerintah.perencanaan',['id'=>Crypt::encryptString(0), 'idsasaran'=>Crypt::encryptString(0)]) }}"><div class="box">
                                  <img src="{{ asset('images/perencanaankerja.png') }}"  style="width: 100px; height: auto">
                                </div></a>
                              
                                
                              </div>
                              <div class="col-md-4">
                              </div>
                            </div>
                            
                            <div class="col-md-12">
                              <div class="portfolio-item bootstrap wordpress col-xs-6 col-sm-4 col-md-1">
                              </div>
                              <div class="portfolio-item bootstrap wordpress col-xs-6 col-sm-4 col-md-1">
                                <a href="{{ route('pemerintah.pelaporan',['id'=>Crypt::encryptString(0), 'idsasaran'=>Crypt::encryptString(0)]) }}"><div class="box">
                                  <img src="{{ asset('images/pelaporankinerja.png') }}"  style="width: 100px; height: auto">
                                </div></a>
                              
                              </div>
                              <div class="col-md-5">
                              </div>
                              <div class="portfolio-item joomla bootstrap col-xs-6 col-sm-4 col-md-2">
                              
                                <a href="{{ route('pemerintah.pengukuran',['id'=>Crypt::encryptString(0), 'idsasaran'=>Crypt::encryptString(0)]) }}"><div class="box">
                                  <img src="{{ asset('images/pengukurankerja.png') }}"  style="width: 100px; height: auto">
                                </div></a>
                              
                              </div>
                              <!--/.portfolio-item-->
                            </div>
                            

                            <div class="col-md-12">
                              <div class="col-md-4">
                              </div>
                                <div class="portfolio-item joomla wordpress apps col-xs-6 col-sm-4 col-md-2">
                                
                                <a href="{{ route('pemerintah.evaluasi') }}"><div class="box">
                                  <img src="{{ asset('images/evaluasikerja.png') }}"  style="width: 100px; height: auto">
                                </div></a>
                              
                                </div>
                              <div class="col-md-4">
                              </div>
                            </div>	


                        </div>
					
                    </div>

                    

               </div>
          </div>
     </section>


     <!-- CONTACT -->
     <section data-stellar-background-ratio="0.5" style="margin-top: -85px !important">	  
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3961.166936441682!2d107.55264901477257!3d-6.870591195035049!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e68e43e4d3ab263%3A0x485bd63d0648c89b!2sPemkot+Cimahi!5e0!3m2!1sid!2sid!4v1550913647325" width="100%" height="380"  frameborder="2" style="border:0; margin-bottom: -85px !important" allowfullscreen></iframe>
		
     </section>


     @endsection

@section('customjs')
@endsection