routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', function () {
	// return redirect()->route('login');
	return redirect()->route('pemerintah.index');
})->name('/');


Route::group(['as' => 'auth.'], function (){
	Route::post('auth/login', 'Auth\LoginController@login')->name('login');
});

Route::group(['as' => 'pemerintah.'], function (){

	Route::get('index', 'Backend\PemerintahController@index')->name('index');
	Route::get('about', 'Backend\PemerintahController@about')->name('about');
	Route::get('contact', 'Backend\PemerintahController@contact')->name('contact');
	Route::get('detaildinas', 'Backend\PemerintahController@detaildinas')->name('detaildinas');
	Route::get('iku', 'Backend\PemerintahController@iku')->name('iku');
	Route::get('rkt', 'Backend\PemerintahController@rkt')->name('rkt');
	Route::get('pk', 'Backend\PemerintahController@pk')->name('pk');
	Route::get('pkperubahan', 'Backend\PemerintahController@pkperubahan')->name('pkperubahan');
	Route::get('rencanaaksi', 'Backend\PemerintahController@rencanaaksi')->name('rencanaaksi');
	Route::get('program', 'Backend\PemerintahController@program')->name('program');
	Route::get('detailpelaporan', 'Backend\PemerintahController@detailpelaporan')->name('detailpelaporan');
	Route::get('detailpengukuran', 'Backend\PemerintahController@detailpengukuran')->name('detailpengukuran');


	// Route::get('changetahun/{tahun}', 'Backend\PemerintahController@changetahun')->name('changetahun');
	Route::any('gantitahun/{tahun}', 'Backend\PemerintahController@gantitahun')->name('gantitahun');

	Route::any('perencanaan/{id}/{idsasaran}/{idjabatan}', 'Backend\PemerintahController@perencanaan')->name('perencanaan');
	Route::any('pengukuran/{id}/{idsasaran}', 'Backend\PemerintahController@pengukuran')->name('pengukuran');
	Route::any('pelaporan/{id}/{idsasaran}', 'Backend\PemerintahController@pelaporan')->name('pelaporan');
	Route::any('evaluasi', 'Backend\PemerintahController@evaluasi')->name('evaluasi');
});


Auth::routes();

Route::group([
	'namespace' => 'Backend',
	'prefix' => 'backend',
	'as' => 'backend.',
	'middleware' => 'auth',
], function () {

	// Route::get('home', 'HomeController@index')->name('home')->middleware('auth-menu');
	Route::get('home', 'HomeController@index')->name('home');



    /*
	 * RPJMD/RENSTRA Modul Routes
	 * route('web.rpjmd')
	 * route('web.rpjmd.detail')
	 */
	Route::group(['as' => 'rpjmd.'], function (){
		Route::get('rpjmd', 'RpjmdController@index')->name('index');
		Route::get('rpjmd/masukoperator', 'RpjmdController@masukoperator')->name('masukoperator');
		Route::get('rpjmd/masuk/{id}/{tahun}', 'RpjmdController@masuk')->name('masuk');
		Route::get('rpjmd/visidetail/{id}/{ids}', 'RpjmdController@visidetail')->name('visidetail');
		Route::get('rpjmd/tambahmisi/{id}/{ids}', 'RpjmdController@tambahmisi')->name('tambahmisi');
		Route::get('rpjmd/tambahtujuan/{id}/{ids}', 'RpjmdController@tambahtujuan')->name('tambahtujuan');
		Route::get('rpjmd/tambahindikatortujuan/{id}/{ids}', 'RpjmdController@tambahindikatortujuan')->name('tambahindikatortujuan');
		Route::get('rpjmd/tambahindikatorsasaran/{id}/{ids}', 'RpjmdController@tambahindikatorsasaran')->name('tambahindikatorsasaran');
		Route::get('rpjmd/tambahsasaran/{id}/{ids}', 'RpjmdController@tambahsasaran')->name('tambahsasaran');
		Route::get('rpjmd/tambahprogram/{id}/{ids}', 'RpjmdController@tambahprogram')->name('tambahprogram');
		Route::get('rpjmd/misidetail/{id}/{ids}', 'RpjmdController@misidetail')->name('misidetail');
		Route::get('rpjmd/tujuandetail/{id}/{ids}', 'RpjmdController@tujuandetail')->name('tujuandetail');
		Route::get('rpjmd/sasarandetail/{id}/{ids}', 'RpjmdController@sasarandetail')->name('sasarandetail');
		Route::get('rpjmd/detailsasaranindikator/{id}/{ids}', 'RpjmdController@detailsasaranindikator')->name('detailsasaranindikator');
		Route::get('rpjmd/detailtujuanindikator/{id}/{ids}', 'RpjmdController@detailtujuanindikator')->name('detailtujuanindikator');
		Route::get('rpjmd/tujuan/{id}/{tahun}/{ids}', 'RpjmdController@tujuan')->name('tujuan');
		Route::get('rpjmd/program/{id}/{ids}', 'RpjmdController@program')->name('program');
		Route::post('rpjmd/deletevisi', 'RpjmdController@deletevisi')->name('deletevisi');
		Route::post('rpjmd/deletemisi', 'RpjmdController@deletemisi')->name('deletemisi');
		Route::post('rpjmd/deletetujuan', 'RpjmdController@deletetujuan')->name('deletetujuan');
		Route::post('rpjmd/deletesasaran', 'RpjmdController@deletesasaran')->name('deletesasaran');
		Route::post('rpjmd/deleteindikatorsasaran', 'RpjmdController@deleteindikatorsasaran')->name('deleteindikatorsasaran');
		Route::post('rpjmd/savevisi', 'RpjmdController@savevisi')->name('savevisi');
		Route::post('rpjmd/editvisi', 'RpjmdController@editvisi')->name('editvisi');
		Route::post('rpjmd/savemisi', 'RpjmdController@savemisi')->name('savemisi');
		Route::post('rpjmd/editmisi', 'RpjmdController@editmisi')->name('editmisi');
		Route::post('rpjmd/savetujuan', 'RpjmdController@savetujuan')->name('savetujuan');
		Route::post('rpjmd/edittujuan', 'RpjmdController@edittujuan')->name('edittujuan');
		Route::post('rpjmd/editindikatortujuan', 'RpjmdController@editindikatortujuan')->name('editindikatortujuan');
		Route::post('rpjmd/rubahiku', 'RpjmdController@rubahiku')->name('rubahiku');
		Route::post('rpjmd/deleteinditujuan', 'RpjmdController@deleteinditujuan')->name('deleteinditujuan');
		Route::post('rpjmd/saveindikatortujuan', 'RpjmdController@saveindikatortujuan')->name('saveindikatortujuan');
		Route::post('rpjmd/savesasaran', 'RpjmdController@savesasaran')->name('savesasaran');
		Route::post('rpjmd/editsasaran', 'RpjmdController@editsasaran')->name('editsasaran');
		Route::post('rpjmd/editindikatorsasaran', 'RpjmdController@editindikatorsasaran')->name('editindikatorsasaran');
		Route::post('rpjmd/saveindikatorsasaran', 'RpjmdController@saveindikatorsasaran')->name('saveindikatorsasaran');
		Route::post('rpjmd/saveprogram', 'RpjmdController@saveprogram')->name('saveprogram');
		// Route::get('role/edit/{id}', 'RoleController@edit')->name('edit');
		// Route::post('role/update/{id}', 'RoleController@update')->name('update');
		// Route::get('role/delete/{id}', 'RoleController@delete')->name('delete');
	});

	/**
	 * Change Password Modul Routes
	 * route('backend.change-password.*')
	 */
	Route::group(['as' => 'change-password.'], function (){
		Route::get('change-password', 'ChangePasswordController@index')->name('index');
		Route::post('change-password/change', 'ChangePasswordController@change')->name('change');
	});

	/**
	 * Profile Modul Routes
	 * route('backend.profile.*')
	 */
	Route::group(['as' => 'profile.'], function (){
		Route::get('profile', 'ProfileController@index')->name('index');
		Route::post('profile/update', 'ProfileController@update')->name('update');
	});

	/**
	 * User Modul Routes
	 * route('backend.user.*')
	 */
	Route::group(['as' => 'user.'], function (){
		Route::get('user', 'UserController@index')->name('index');
		Route::post('user/toggle', 'UserController@toggle')->name('toggle');
		Route::get('user/create', 'UserController@create')->name('create');
		Route::post('user/store', 'UserController@store')->name('store');
		Route::get('user/edit/{id}', 'UserController@edit')->name('edit');
		Route::get('editprofile/edit/{id}', 'UserController@editprofile')->name('editprofile');
		Route::post('user/update/{id}', 'UserController@update')->name('update');
	});

	/**
	 * Roles Modul Routes
	 * route('backend.role.*')
	 */
	Route::group(['as' => 'role.'], function (){
		Route::get('role', 'RoleController@index')->name('index')->middleware('auth-menu');
		Route::post('role/toggle', 'RoleController@toggle')->name('toggle');
		Route::get('role/create', 'RoleController@create')->name('create');
		Route::post('role/store', 'RoleController@store')->name('store');
		Route::get('role/edit/{id}', 'RoleController@edit')->name('edit');
		Route::post('role/update/{id}', 'RoleController@update')->name('update');
	});

	/**
	 * Menus Modul Routes
	 * route('backend.menu.*')
	 */
	Route::group(['as' => 'menu.'], function (){
		Route::get('menu', 'MenuController@index')->name('index');
		Route::post('menu/toggle', 'MenuController@toggle')->name('toggle');
		Route::get('menu/create', 'MenuController@create')->name('create');
		Route::post('menu/store', 'MenuController@store')->name('store');
		Route::get('menu/edit/{id}', 'MenuController@edit')->name('edit');
		Route::post('menu/update/{id}', 'MenuController@update')->name('update');
	});

	/**
	 * Access Control Modul Routes
	 * route('backend.accesscontrol.*')
	 */
	Route::group(['as' => 'accesscontrol.'], function (){
		Route::get('accesscontrol', 'AccessControlController@index')->name('index');
		Route::post('accesscontrol/update', 'AccessControlController@update')->name('update');
	});

	 /*
	 * Dinas Modul Routes
	 * route('web.dinas')
	 * route('web.dinas.detail')
	 */
		Route::group(['as' => 'dinas.'], function (){
			Route::get('dinas', 'DinasController@index')->name('index');
			Route::get('dinas/tambahdinas', 'DinasController@tambahdinas')->name('tambahdinas');
			Route::get('dinas/copydinas', 'DinasController@copydinas')->name('copydinas');
			Route::get('dinas/editdinas/{id}', 'DinasController@editdinas')->name('editdinas');
			Route::get('dinas/eselon/{id}', 'DinasController@eselon')->name('eselon');
			Route::get('dinas/tambaheselon/{id}', 'DinasController@tambaheselon')->name('tambaheselon');
			Route::get('dinas/addeselon/{id}/{ids}', 'DinasController@addeselon')->name('addeselon');

app/Models/Dinas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer $id
 * @property int $parent
 * @property string $name
 * @property string $address
 * @property string $description
 * @property int $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property Department[] $departments
 * @property MeetingRoom[] $meetingRooms
 * @property Person[] $persons
 * @property User[] $users
 * @property Visit[] $visits
 */
class Dinas extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
    
    /**
     * The "type" of the auto-incrementing ID.
     * 
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * @var array
     */
    protected $fillable = ['parent', 'name', 'address', 'description', 'status', 'created_at', 'updated_at', 'deleted_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function users()
    {
        return $this->hasMany('App\Models\User');
    }
}

app/Http/Controllers/Backend/AccessControlController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\AccessControl\AccessControlRepositoryInterface;
use App\Repositories\Role\RoleRepositoryInterface;
use App\Traits\FlashMessageTraits;
use DB;
class AccessControlController extends Controller
{
    use FlashMessageTraits;

    function __construct(
        AccessControlRepositoryInterface $accessControlRepo,
        RoleRepositoryInterface $roleRepo
    )
	{
        $this->accessControlRepo = $accessControlRepo;
        $this->roleRepo = $roleRepo;
        
        //No session access from constructor work arround
        $this->middleware(function ($request, $next)
        {
            $this->user = session('data')->user;
            return $next($request);
        });
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $request = request();
        
        // If request id is unset
        (!isset($request->id)) ? $role_id = $this->user->role_id : $role_id = $this->decryptingId($request->id) ;

        $roles = DB::select("SELECT * FROM roles WHERE status = 1 and id not in(99) order by role asc");
        $access = $this->accessControlRepo->access($role_id);

        return
            view('backend.accesscontrol.index')
            ->with('roles', $roles)
            ->with('accesscontrols', $access)
        ;
    }

    /**
     * 
     */
    public function update(Request $request)
    {
        $request->merge(['role' => $this->decryptingId($request->role) ]);
        $response = $this->accessControlRepo->update($request);
        $this->message($response->level, $response->message);
        return back();
    }

}

app/Http/Controllers/Backend/ChangePasswordController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\User\UserRepositoryInterface;
use App\Traits\FlashMessageTraits;
use Auth;

class ChangePasswordController extends Controller
{
    use FlashMessageTraits;

    function __construct(
        UserRepositoryInterface $userRepo
    ) {
        $this->userRepo     = $userRepo;
        $this->_pass_regex  = config('setting.pass.regex');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return
            view('backend.change-password')
        ;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function change(Request $request)
    {
        //
        $request->validate([
            'current_password' => 'required',
            'new_password' => 'required|string|min:8|confirmed|'.$this->_pass_regex,
        ]);
        $id = Auth::user()->id;
        $response = $this->userRepo->changePassword($id, $request);
        $this->message($response->level, $response->message);
        return redirect()->route('backend.change-password.index');
    }

    

}

app/Http/Controllers/Backend/EvaluasikinerjaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use App\Models\User;
use App\Models\UserValidation;
use App\Models\Role;
use Carbon\Carbon;
use DB;
/**
 * Class UserController.
 */
class EvaluasikinerjaController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */

	function __construct()
	{
		$this->middleware(['auth']);
	}

	public function index()
    {
		$data['breadcrumb'] = [
            'parent' => 'Evaluasi Kinerja',
            'child' => 'List Evaluasi Mandiri'
		];

		$data['listdinas'] = $this->listdinas();
		return view('backend.evaluasikinerja.index', $data);
	}


	public function detail($id, $tahun)
    {
		$query = DB::select("SELECT * FROM tbl_evaluasi WHERE iddinas = ".$id." AND tahun = ".$_COOKIE['tahun']);
		$data['evaluasi'] = $query;
        $data['id'] = $id;

		return view('backend.evaluasikinerja.detail', $data);
	}

	public function listdinas(){
		$hasil = DB::select('SELECT aa.td_id, aa.td_dinas, aa.td_keterangan , bb.nilai
								FROM
										(
										SELECT a.td_id, a.td_dinas, a.td_keterangan
										FROM tbl_dinas a
										WHERE
											a.status = 1

                                            and deleted_at is not null
										)aa
								LEFT JOIN
										(
										SELECT a.td_id, a.td_dinas, a.td_keterangan , b.nilai
										FROM tbl_dinas a
										LEFT JOIN tbl_evaluasi b on a.td_id = b.iddinas
										where
											status = 1

                                            and deleted_at is null
											AND b.tahun = '.$_COOKIE['tahun'].'
										)bb on bb.td_id = aa.td_id ');
		return $hasil;
	}


	public function nilaievaluasiedit(Request $request){
		$input = $request->all();
		$data = DB::table('tbl_evaluasi')
				->where('iddinas', $input['idsasaran'])
				->where('tahun', $input['tahun'])
				->update(['nilai' => $input['target']]);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'Nilai Sukses Terupdate!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'Error Ketika Memasukan Ke Database' );
			return response()->json($result);
		}
	}


	public function nilaievaluasi(Request $request){
		$input = $request->all();
		$data = DB::table('tbl_evaluasi')->insert(
			['iddinas' => $input['idsasaran'], 'nilai' => $input['target'], 'tahun' => $input['tahun']]
		);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'Nilai Sukses Tersimpan!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'Error Ketika Memasukan Ke Database' );
			return response()->json($result);
		}
	}

}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.home.home');
    }
}

resources/views/backend/dinas/create.blade.php
<div class="form-horizontal" >
    <div class="form-group">
        <label class="col-md-12 control-label">Nama Perangkat Daerah*</label>
        <div class="col-md-12">
            <input class="form-control" id="dinas" misi="dinas" placeholder="dinas..." required>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-12 control-label">Keterangan*</label>
        <div class="col-md-12">
            <textarea class="form-control" rows="5" id="ket" misi="ket" placeholder="keterangan..." required></textarea>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-md-12 control-label">Index</label>
        <div class="col-md-12">
            <input class="form-control" id="index" misi="index" placeholder="index..." required>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-12 col-md-8">
            <button type="button" onClick="tambahDinas()" class="btn btn-primary waves-effect waves-light btn-rounded">
                Simpan
            </button>
        </div>
    </div>
</div>

<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    function tambahDinas(){
        var dinas   = $('#dinas').val();
        var ket   = $('#ket').val();
        var index   = $('#index').val();
        
        if(dinas){
            if(ket){
                    var datapost={
                        "dinas"  :   dinas,
                        "ket"  :   ket,
                        "index"  :   index
                    };
                    $.ajax({
                        type: "POST",
                        url: '{{ route("backend.dinas.dinastambah") }}',
                        data : JSON.stringify(datapost),
                        dataType: 'json',
                        contentType: 'application/json; charset=utf-8',
                        success: function(response) {
                            if (response.success == true) {
                                $("#panel-modal .close").click();
                                swal({
                                    title: 'Success!',
                                    text: response.message,
                                    type: 'success',
                                    showCancelButton: false,
                                    confirmButtonText: 'Ok'
                                }).then(function () {
                                    window.location.href = '{{ route("backend.dinas.index") }}';
                                })



                            } else{
                            swal("Failed!", response.message, "error");
                            }
                        }
                    });
            }else{
                swal("Failed!", "Keterangan Belum Terisi!", "error");
            }  
        
        
        }else{
            swal("Failed!", "Dinas Belum Terisi!", "error");
        }
          
    }
</script>

resources/views/backend/dinas/index.blade.php
@extends('backend.layouts.app')

@section('title', 'Home')

@section('content')
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">
                                List Dinas
                            </h3>
                        </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="row">
                        <div class="col-lg-12">

                            <div class="ibox-tools right">
                                <a class="btn btn-default btn-xs" type="button" onClick="tambahDinass()" href="javascript:void(0)">
                                    <i class="fa fa-plus"></i>
                                    <strong>New</strong>
                                </a>
                            </div>
                            <table id="listkota" class="table ">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Perangkat Daerah</th>
                                        <th>Action</th>
                                    </tr>
                                    <tbody>
                                        @php($sl=1)
                                            @foreach($listdinas as $dinas)
                                            <tr>
                                                <td>{{$sl}}</td>
                                                <td>{{$dinas->td_dinas}}</td>
                                                <td>
                                                    <a href="javascript:void(0)" onClick="copyDinas({{$dinas->td_id}}, '{{$dinas->td_dinas}}')" placeholder="Copy dari {{$_COOKIE['tahun']-1}}"  type="button" class="btn btn-success btn-icon">
                                                        <i class="fa fa-solid fa-copy"></i>
                                                    </a>
                                                    <a href="javascript:void(0)" onClick="editDinas({{$dinas->td_id}})" type="button" class="btn btn-info btn-icon">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    <a href='{{ route("backend.dinas.eselon", $dinas->td_id) }}' type="button" class="btn btn-info btn-icon">
                                                        <i class="fa fa-eye"></i>
                                                    </a>
                                                    <a href="javascript:void(0)" onClick="deleteDinas({{$dinas->td_id}})" type="button" class="btn btn-danger btn-icon">
                                                        <i class="fa fa-trash"></i>
                                                    </a>

                                                </td>
                                            </tr>

                                            @php($sl++)
                                        @endforeach

                                    </tbody>

                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="panel-modal" class="modal fade" id="kt_modal_1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>
@endsection

@section('onpage-js')
@include('backend.layouts.message')
<script>
   $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $( document ).ready(function() {

    });

    function tambahDinass(){
        var url = '{{ route("backend.dinas.tambahdinas") }}';
        $('#panel-modal').removeData('bs.modal');
        $('#panel-modal  .modal-body').html('<i class="fa fa-cog fa-spin fa-2x fa-fw"></i> Loading...');
        $('#panel-modal  .modal-body').load(url);
        $('#panel-modal  .modal-title').html('<i class="fa fa-pencil"></i> Tambah Perangkat Daerah');
        $('#panel-modal').modal({backdrop:'static',keyboard:false},'show');
    }



    function editDinas(id){
        var url = '{{ route("backend.dinas.editdinas",["id"=>":id"]) }}'
        url = url.replace(':id', id);
        $('#panel-modal').removeData('bs.modal');
        $('#panel-modal  .modal-body').html('<i class="fa fa-cog fa-spin fa-2x fa-fw"></i> Loading...');
        $('#panel-modal  .modal-body').load(url);
        $('#panel-modal  .modal-title').html('<i class="fa fa-pencil"></i> Edit Perangkat Daerah');
        $('#panel-modal').modal({backdrop:'static',keyboard:false},'show');
    }


    function deleteDinas(id){
        swal({
            title: 'Apa anda yakin?',
              text: "Anda akan menghapus dinas!",
              type: 'error',
              showCancelButton: true,
              confirmButtonText: 'Ok'
        }).then(function () {
            var datapost={
                "id"  :   id
              };
              $.ajax({
                type: "POST",
                url: '{{ route("backend.dinas.dinasdelete") }}',
                data : JSON.stringify(datapost),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function(response) {
                  if (response.success == true) {

                      swal({
                            title: 'Success!',
                            text: response.message,
                            type: 'success',
                            showCancelButton: false,
                            confirmButtonText: 'Ok'
                        }).then(function () {
                            window.location.href = "{{url()->current()}}";
                        })



                  } else{
                    swal("Failed!", response.message, "error");
                  }
                }
              });
        })
    }

    function copyDinas(id, name){
        swal({
            title: 'Apa anda yakin?',
              text: "Anda akan mengcopy dinas "+name+" tahun {{ $_COOKIE['tahun'] - 1}}",
              icon: 'info',
              showCancelButton: true,
              confirmButtonText: 'Ok'
        }).then(function () {
            var datapost={
                "id"  :   id,
                "tahun": {{ $_COOKIE['tahun'] - 1}}
              };
              $.ajax({
                type: "POST",
                url: '{{ route("backend.dinas.copydinas") }}',
                data : JSON.stringify(datapost),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function(response) {
                  if (response.success == true) {

                      swal({
                            title: 'Success!',
                            text: response.message,
                            type: 'success',
                            showCancelButton: false,
                            confirmButtonText: 'Ok'
                        }).then(function () {
                            window.location.href = "{{url()->current()}}";
                        })



                  } else{
                    swal("Failed!", response.message, "error");
                  }
                }
              });
        })
    }
</script>
@endsection