routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', function () {
	// return redirect()->route('login');
	return redirect()->route('pemerintah.index');
})->name('/');


Route::group(['as' => 'auth.'], function (){
	Route::post('auth/login', 'Auth\LoginController@login')->name('login');
});

Route::group(['as' => 'pemerintah.'], function (){

	Route::get('index', 'Backend\PemerintahController@index')->name('index');
	Route::get('about', 'Backend\PemerintahController@about')->name('about');
	Route::get('contact', 'Backend\PemerintahController@contact')->name('contact');
	Route::get('detaildinas', 'Backend\PemerintahController@detaildinas')->name('detaildinas');
	Route::get('iku', 'Backend\PemerintahController@iku')->name('iku');
	Route::get('rkt', 'Backend\PemerintahController@rkt')->name('rkt');
	Route::get('pk', 'Backend\PemerintahController@pk')->name('pk');
	Route::get('pkperubahan', 'Backend\PemerintahController@pkperubahan')->name('pkperubahan');
	Route::get('rencanaaksi', 'Backend\PemerintahController@rencanaaksi')->name('rencanaaksi');
	Route::get('program', 'Backend\PemerintahController@program')->name('program');
	Route::get('detailpelaporan', 'Backend\PemerintahController@detailpelaporan')->name('detailpelaporan');
	Route::get('detailpengukuran', 'Backend\PemerintahController@detailpengukuran')->name('detailpengukuran');


	// Route::get('changetahun/{tahun}', 'Backend\PemerintahController@changetahun')->name('changetahun');
	Route::any('gantitahun/{tahun}', 'Backend\PemerintahController@gantitahun')->name('gantitahun');

	Route::any('perencanaan/{id}/{idsasaran}/{idjabatan}', 'Backend\PemerintahController@perencanaan')->name('perencanaan');
	Route::any('pengukuran/{id}/{idsasaran}', 'Backend\PemerintahController@pengukuran')->name('pengukuran');
	Route::any('pelaporan/{id}/{idsasaran}', 'Backend\PemerintahController@pelaporan')->name('pelaporan');
	Route::any('evaluasi', 'Backend\PemerintahController@evaluasi')->name('evaluasi');
});


Auth::routes();

Route::group([
	'namespace' => 'Backend',
	'prefix' => 'backend',
	'as' => 'backend.',
	'middleware' => 'auth',
], function () {

	// Route::get('home', 'HomeController@index')->name('home')->middleware('auth-menu');
	Route::get('home', 'HomeController@index')->name('home');



    /*
	 * RPJMD/RENSTRA Modul Routes
	 * route('web.rpjmd')
	 * route('web.rpjmd.detail')
	 */
	Route::group(['as' => 'rpjmd.'], function (){
		Route::get('rpjmd', 'RpjmdController@index')->name('index');
		Route::get('rpjmd/masukoperator', 'RpjmdController@masukoperator')->name('masukoperator');
		Route::get('rpjmd/masuk/{id}/{tahun}', 'RpjmdController@masuk')->name('masuk');
		Route::get('rpjmd/visidetail/{id}/{ids}', 'RpjmdController@visidetail')->name('visidetail');
		Route::get('rpjmd/tambahmisi/{id}/{ids}', 'RpjmdController@tambahmisi')->name('tambahmisi');
		Route::get('rpjmd/tambahtujuan/{id}/{ids}', 'RpjmdController@tambahtujuan')->name('tambahtujuan');
		Route::get('rpjmd/tambahindikatortujuan/{id}/{ids}', 'RpjmdController@tambahindikatortujuan')->name('tambahindikatortujuan');
		Route::get('rpjmd/tambahindikatorsasaran/{id}/{ids}', 'RpjmdController@tambahindikatorsasaran')->name('tambahindikatorsasaran');
		Route::get('rpjmd/tambahsasaran/{id}/{ids}', 'RpjmdController@tambahsasaran')->name('tambahsasaran');
		Route::get('rpjmd/tambahprogram/{id}/{ids}', 'RpjmdController@tambahprogram')->name('tambahprogram');
		Route::get('rpjmd/misidetail/{id}/{ids}', 'RpjmdController@misidetail')->name('misidetail');
		Route::get('rpjmd/tujuandetail/{id}/{ids}', 'RpjmdController@tujuandetail')->name('tujuandetail');
		Route::get('rpjmd/sasarandetail/{id}/{ids}', 'RpjmdController@sasarandetail')->name('sasarandetail');
		Route::get('rpjmd/detailsasaranindikator/{id}/{ids}', 'RpjmdController@detailsasaranindikator')->name('detailsasaranindikator');
		Route::get('rpjmd/detailtujuanindikator/{id}/{ids}', 'RpjmdController@detailtujuanindikator')->name('detailtujuanindikator');
		Route::get('rpjmd/tujuan/{id}/{tahun}/{ids}', 'RpjmdController@tujuan')->name('tujuan');
		Route::get('rpjmd/program/{id}/{ids}', 'RpjmdController@program')->name('program');
		Route::post('rpjmd/deletevisi', 'RpjmdController@deletevisi')->name('deletevisi');
		Route::post('rpjmd/deletemisi', 'RpjmdController@deletemisi')->name('deletemisi');
		Route::post('rpjmd/deletetujuan', 'RpjmdController@deletetujuan')->name('deletetujuan');
		Route::post('rpjmd/deletesasaran', 'RpjmdController@deletesasaran')->name('deletesasaran');
		Route::post('rpjmd/deleteindikatorsasaran', 'RpjmdController@deleteindikatorsasaran')->name('deleteindikatorsasaran');
		Route::post('rpjmd/savevisi', 'RpjmdController@savevisi')->name('savevisi');
		Route::post('rpjmd/editvisi', 'RpjmdController@editvisi')->name('editvisi');
		Route::post('rpjmd/savemisi', 'RpjmdController@savemisi')->name('savemisi');
		Route::post('rpjmd/editmisi', 'RpjmdController@editmisi')->name('editmisi');
		Route::post('rpjmd/savetujuan', 'RpjmdController@savetujuan')->name('savetujuan');
		Route::post('rpjmd/edittujuan', 'RpjmdController@edittujuan')->name('edittujuan');
		Route::post('rpjmd/editindikatortujuan', 'RpjmdController@editindikatortujuan')->name('editindikatortujuan');
		Route::post('rpjmd/rubahiku', 'RpjmdController@rubahiku')->name('rubahiku');
		Route::post('rpjmd/deleteinditujuan', 'RpjmdController@deleteinditujuan')->name('deleteinditujuan');
		Route::post('rpjmd/saveindikatortujuan', 'RpjmdController@saveindikatortujuan')->name('saveindikatortujuan');
		Route::post('rpjmd/savesasaran', 'RpjmdController@savesasaran')->name('savesasaran');
		Route::post('rpjmd/editsasaran', 'RpjmdController@editsasaran')->name('editsasaran');
		Route::post('rpjmd/editindikatorsasaran', 'RpjmdController@editindikatorsasaran')->name('editindikatorsasaran');
		Route::post('rpjmd/saveindikatorsasaran', 'RpjmdController@saveindikatorsasaran')->name('saveindikatorsasaran');
		Route::post('rpjmd/saveprogram', 'RpjmdController@saveprogram')->name('saveprogram');
		// Route::get('role/edit/{id}', 'RoleController@edit')->name('edit');
		// Route::post('role/update/{id}', 'RoleController@update')->name('update');
		// Route::get('role/delete/{id}', 'RoleController@delete')->name('delete');
	});

	/**
	 * Change Password Modul Routes
	 * route('backend.change-password.*')
	 */
	Route::group(['as' => 'change-password.'], function (){
		Route::get('change-password', 'ChangePasswordController@index')->name('index');
		Route::post('change-password/change', 'ChangePasswordController@change')->name('change');
	});

	/**
	 * Profile Modul Routes
	 * route('backend.profile.*')
	 */
	Route::group(['as' => 'profile.'], function (){
		Route::get('profile', 'ProfileController@index')->name('index');
		Route::post('profile/update', 'ProfileController@update')->name('update');
	});

	/**
	 * User Modul Routes
	 * route('backend.user.*')
	 */
	Route::group(['as' => 'user.'], function (){
		Route::get('user', 'UserController@index')->name('index');
		Route::post('user/toggle', 'UserController@toggle')->name('toggle');
		Route::get('user/create', 'UserController@create')->name('create');
		Route::post('user/store', 'UserController@store')->name('store');
		Route::get('user/edit/{id}', 'UserController@edit')->name('edit');
		Route::get('editprofile/edit/{id}', 'UserController@editprofile')->name('editprofile');
		Route::post('user/update/{id}', 'UserController@update')->name('update');
	});

	/**
	 * Roles Modul Routes
	 * route('backend.role.*')
	 */
	Route::group(['as' => 'role.'], function (){
		Route::get('role', 'RoleController@index')->name('index')->middleware('auth-menu');
		Route::post('role/toggle', 'RoleController@toggle')->name('toggle');
		Route::get('role/create', 'RoleController@create')->name('create');
		Route::post('role/store', 'RoleController@store')->name('store');
		Route::get('role/edit/{id}', 'RoleController@edit')->name('edit');
		Route::post('role/update/{id}', 'RoleController@update')->name('update');
	});

	/**
	 * Menus Modul Routes
	 * route('backend.menu.*')
	 */
	Route::group(['as' => 'menu.'], function (){
		Route::get('menu', 'MenuController@index')->name('index');
		Route::post('menu/toggle', 'MenuController@toggle')->name('toggle');
		Route::get('menu/create', 'MenuController@create')->name('create');
		Route::post('menu/store', 'MenuController@store')->name('store');
		Route::get('menu/edit/{id}', 'MenuController@edit')->name('edit');
		Route::post('menu/update/{id}', 'MenuController@update')->name('update');
	});

	/**
	 * Access Control Modul Routes
	 * route('backend.accesscontrol.*')
	 */
	Route::group(['as' => 'accesscontrol.'], function (){
		Route::get('accesscontrol', 'AccessControlController@index')->name('index');
		Route::post('accesscontrol/update', 'AccessControlController@update')->name('update');
	});

	 /*
	 * Dinas Modul Routes
	 * route('web.dinas')
	 * route('web.dinas.detail')
	 */
		Route::group(['as' => 'dinas.'], function (){
			Route::get('dinas', 'DinasController@index')->name('index');
			Route::get('dinas/tambahdinas', 'DinasController@tambahdinas')->name('tambahdinas');
			Route::get('dinas/copydinas', 'DinasController@copydinas')->name('copydinas');
			Route::get('dinas/editdinas/{id}', 'DinasController@editdinas')->name('editdinas');
			Route::get('dinas/eselon/{id}', 'DinasController@eselon')->name('eselon');
			Route::get('dinas/tambaheselon/{id}', 'DinasController@tambaheselon')->name('tambaheselon');
			Route::get('dinas/addeselon/{id}/{ids}', 'DinasController@addeselon')->name('addeselon');

app/Http/Controllers/Backend.bak/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\User\UserRepositoryInterface;
use App\Repositories\Role\RoleRepositoryInterface;
use App\Repositories\Company\CompanyRepositoryInterface;
use App\Traits\FlashMessageTraits;
use DB;
class UserController extends Controller
{
    use FlashMessageTraits;

    function __construct(
        UserRepositoryInterface $userRepo,
        RoleRepositoryInterface $roleRepo,
        CompanyRepositoryInterface $companyRepo
    ) {
        $this->userRepo     = $userRepo;
        $this->roleRepo     = $roleRepo;
        $this->companyRepo  = $companyRepo;
        $this->_pass_regex  = config('setting.pass.regex');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = $this->userRepo->pagination(10);
        return
            view('backend.user.index')
            ->with('users', $data->datas)
            ->with('status', $data->status)
        ;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		$data['breadcrumb'] = [
            'parent' => 'User Management',
            'child' => 'Create New User'
        ];
        $dinas = DB::select("SELECT * FROM tbl_dinas WHERE status = 1 order by `index` asc");
        $role = DB::select("SELECT * FROM roles WHERE status = 1 and id not in(99) order by role asc");
        return
            view('backend.user.create', $data)
            ->with('roles', $role)
            ->with('dinas', $dinas)
        ;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'role_id' => 'required',
            'name' => 'required|string|max:191',
            'email' => 'required|string|email|max:191|unique:users',
            'password' => 'required|string|min:8|confirmed|'.$this->_pass_regex,
        ]);
        $response = $this->userRepo->store($request);
        $this->message($response->level, $response->message);
        return redirect()->route('backend.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $id = $this->decryptingId($id);
        $dinas = DB::select("SELECT * FROM tbl_dinas WHERE status = 1 and td_id not in(1)");
        $role = DB::select("SELECT * FROM roles WHERE status = 1 and id not in(99) order by role asc");
        return
            view('backend.user.edit')
            ->with('detail', $this->userRepo->find($id))
            ->with('roles', $role)
            ->with('dinas', $dinas)
        ;
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function editprofile($id)
    {
        //
        $id = $this->decryptingId($id);
        $dinas = DB::select("SELECT * FROM tbl_dinas WHERE status = 1 and td_id not in(1)");
        $role = DB::select("SELECT * FROM roles WHERE status = 1 and id not in(99) order by role asc");
        return
            view('backend.user.editprofile')
            ->with('detail', $this->userRepo->find($id))
            ->with('roles', $role)
            ->with('dinas', $dinas)
        ;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $id = $this->decryptingId($id);
        
        $request->validate([
            'role_id' => 'required',
            'name' => 'required|string|max:191',
            'email' => 'required|string|email|max:191|unique:users,email,'.$id,
            'password' => 'string|min:8|confirmed|'.$this->_pass_regex,
        ]);
        
        $response = $this->userRepo->update($id, $request);
        $this->message($response->level, $response->message);
        return redirect()->route('backend.user.index');
    }

    public function toggle(Request $request)
    {
        //
        $response = $this->userRepo->toggle($request);
        $this->message($response->level, $response->message);
        return back();
    }

}

app/Http/Controllers/Backend/AccessControlController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\AccessControl\AccessControlRepositoryInterface;
use App\Repositories\Role\RoleRepositoryInterface;
use App\Traits\FlashMessageTraits;
use DB;
class AccessControlController extends Controller
{
    use FlashMessageTraits;

    function __construct(
        AccessControlRepositoryInterface $accessControlRepo,
        RoleRepositoryInterface $roleRepo
    )
	{
        $this->accessControlRepo = $accessControlRepo;
        $this->roleRepo = $roleRepo;
        
        //No session access from constructor work arround
        $this->middleware(function ($request, $next)
        {
            $this->user = session('data')->user;
            return $next($request);
        });
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $request = request();
        
        // If request id is unset
        (!isset($request->id)) ? $role_id = $this->user->role_id : $role_id = $this->decryptingId($request->id) ;

        $roles = DB::select("SELECT * FROM roles WHERE status = 1 and id not in(99) order by role asc");
        $access = $this->accessControlRepo->access($role_id);

        return
            view('backend.accesscontrol.index')
            ->with('roles', $roles)
            ->with('accesscontrols', $access)
        ;
    }

    /**
     * 
     */
    public function update(Request $request)
    {
        $request->merge(['role' => $this->decryptingId($request->role) ]);
        $response = $this->accessControlRepo->update($request);
        $this->message($response->level, $response->message);
        return back();
    }

}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.home.home');
    }
}

resources/views/backend/user/create.blade.php
@extends('backend.layouts.app')

@section('title', 'Create New User')

@section('content')
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="kt-portlet">
                <div class="kt-portlet__body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="ibox float-e-margins">
                                <div class="ibox-title">

                                    <h5>Create New User</h5>
                                    <div class="ibox-tools">

                                        {{-- <a class="collapse-link">
                                            <i class="fa fa-chevron-up"></i>
                                        </a>
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            <i class="fa fa-wrench"></i>
                                        </a>
                                        <ul class="dropdown-menu dropdown-user">
                                            <li><a href="#">Config option 1</a>
                                            </li>
                                            <li><a href="#">Config option 2</a>
                                            </li>
                                        </ul>
                                        <a class="close-link">
                                            <i class="fa fa-times"></i>
                                        </a> --}}
                                    </div>

                                </div>
                                <div class="ibox-content">
                                    <form role="form" action="{{ route('backend.user.store') }}" method="POST">
                                        @csrf

                                        <div class="form-group">
                                            <label>Service Division</label>
                                            <select class="form-control" name="dinas_id" required>
                                                <option value="" disabled selected>Unit Kerja</option>
                                                @foreach ($dinas as $company)
                                                @if(old('company_id') == $company->td_id)
                                                    <option selected value="{{ $company->td_id }}">{{ $company->td_dinas }}</option>
                                                @else
                                                    <option value="{{ $company->td_id }}">{{ $company->td_dinas }}</option>
                                                @endif
                                                @endforeach
                                            </select>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label>Role</label>
                                            <select class="form-control" name="role_id" required>
                                                <option value="" disabled selected>Pilih Role</option>
                                                @foreach ($roles as $role)
                                                @if(old('role_id') == $role->id)
                                                    <option selected value="{{ $role->id }}">{{ $role->role }}</option>
                                                @else
                                                    <option value="{{ $role->id }}">{{ $role->role }}</option>
                                                @endif
                                                @endforeach
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label>Nama</label>
                                            <input type="text" name="name" placeholder="Enter Name" class="form-control" required value="{{ old('name') }}">
                                        </div>

                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" name="email" placeholder="Enter Email" class="form-control" required value="{{ old('email') }}">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" name="password" placeholder="Enter Password" class="form-control" required>
                                        </div>

                                        <div class="form-group">
                                            <label>Retype Password</label>
                                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" placeholder="{{ __('Confirm Password') }}" required>
                                        </div>

                                        <div>
                                            <button class="btn btn-sm btn-success pull-right m-t-n-xs" type="submit">
                                                <strong>SUBMIT</strong>
                                            </button>
                                        </div>

                                    </form>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('onpage-js')

    @include('backend.layouts.message')
    
    <script>
        $(document).ready(function () {
            
        });
    </script>

@endsection

resources/views/backend/user/edit.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="kt-portlet">
                <div class="kt-portlet__body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="ibox float-e-margins">
                                    <div class="ibox-title">

                                        <h3>Edit User <span class="text-info">{{ $detail->name }}</span></h3>
                                        <div class="ibox-tools">

                                        </div>

                                    </div>
                                    <div class="ibox-content">
                                        <form role="form" action="{{ route('backend.user.update', Crypt::encrypt( $detail->id )) }}" method="POST">
                                            @csrf

                                            <div class="form-group">
                                                <label>Service Division</label>
                                                <select class="form-control" name="dinas_id" required>
                                                    <option value="" disabled selected>Choose Division</option>
                                                    @foreach ($dinas as $company)
                                                    @if($detail->dinas_id == $company->td_id)
                                                        <option selected value="{{ $company->td_id }}">{{ $company->td_dinas }}</option>
                                                    @else
                                                        <option value="{{ $company->td_id }}">{{ $company->td_dinas }}</option>
                                                    @endif
                                                    @endforeach
                                                </select>
                                            </div>

                                            <div class="form-group">
                                                <label>Role</label>
                                                <select class="form-control" name="role_id" required>
                                                    <option value="" disabled selected>Choose Role</option>
                                                    @foreach ($roles as $role)
                                                    @if($detail->role_id == $role->id)
                                                        <option selected value="{{ $role->id }}">{{ $role->role }}</option>
                                                    @else
                                                        <option value="{{ $role->id }}">{{ $role->role }}</option>
                                                    @endif
                                                    @endforeach
                                                </select>
                                            </div>

                                            <div class="form-group">
                                                <label>Name</label>
                                                <input type="text" name="name" placeholder="Enter Name" class="form-control" required value="{{ $detail->name }}">
                                            </div>

                                            <div class="form-group">
                                                <label>Email</label>
                                                <input type="email" name="email" placeholder="Enter Email" class="form-control" required value="{{ $detail->email }}">
                                            </div>
                                            
                                            <div class="form-group">
                                                <label>Password</label>
                                                <input type="password" name="password" placeholder="Enter Password" class="form-control" required>
                                                <span class="help-block text-10 text-info">
                                                    Password must be more than 8 characters long, should contain at-least 1 Uppercase, 1 Lowercase, 1 Numeric and 1 special character.
                                                </span>
                                            </div>

                                            <div class="form-group">
                                                <label>Retype Password</label>
                                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" placeholder="{{ __('Confirm Password') }}" required>
                                            </div>

                                            <div>
                                                <button class="btn btn-sm btn-success pull-right m-t-n-xs" type="submit">
                                                    <strong>UPDATE</strong>
                                                </button>
                                            </div>

                                        </form>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@section('onpage-js')

    @include('backend.layouts.message')
    
    <script>
        $(document).ready(function () {
            
        });
    </script>

@endsection